import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export type SwatchProps = {
  color: string;
};

const Swatch: React.FC<SwatchProps> = ({ color }) => {
  console.log(`Swatch Rendered with ${color}`);
  return (
    <div className={`w-16 h-16 m-4`} style={{ backgroundColor: color }}></div>
  );
};

export default function Home() {
  const [appRenderIndex, setAppRenderIndex] = useState(0);
  console.log(`App Rendered ${appRenderIndex}`);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <button
            className="border-2 px-3 py-2 rounded-md bg-emerald-200"
            onClick={() => setAppRenderIndex((prev) => prev + 1)}
          >
            Re-Render App
          </button>
        </div>
        <div>
          <Swatch color={"red"} />
        </div>
      </div>
    </>
  );
}
